### ISSUE TITLE
I'd love to know how to get to interpolate() and single_term() 

### ISSUE THREAD

**Issue by pbalogh** [pim-book/programmers-introduction-to-mathematics#10]
Section 2.4, "Realizing it in Code", assumes that I'll understand how to make the transition away from the sigma-and-pi version of things. I implemented the sigma-and-pi version in Javascript and it looks like a great way to get from any x input to a y output that "belongs to" the polynomial that was "defined" by the initial set of points I gave it. But it looks like all the values in there are those initial x and y values, and the output is a single (new) y value. I don't see how to make the journey from there to getting the array of coefficients that actually make up the "real" polynomial.

**Comment by pbalogh** [comment]
I should note that when I multiply out y1 * ((x - x2)(x-x3)) / ((x1 - x2)(x1 - x3)) .... , I do see how we arrive at a polynomial from the original array of points. What I don't see is how to do that programmatically, much less how single_term isolates the coefficient for a particular power of x in that polynomial.

**Comment by j2kun** [comment]
If I understand correctly, your confusion is that I'm overloading "term" as both "one piece of the sum in the canonical representation of a polynomial", and "one piece of any summed expression".

You think that "singleTerm" should output a single term of the resulting polynomial, i.e.

A * x^j

for some constant A and some power j.

Actually, it's being more direct: singleTerm returns a single term of the _sum_ from the proof of Theorem 2.2 (see the offset equation at the top of page 22; singleTerm outputs one entry of the sum for a fixed i).

It directly translates that expression, and the only rewriting we need is to express the inner-most term of the product

(x - x_i) / (x_i - x_j)

in terms of our Polynomial data structure. And we do that by separating the fraction into a constant term and a degree 1 term: 

Polynomial([-xj / (xi - xj), 1.0 / (xi - xj)])

Does that clear it up? I will make sure this clarification makes it into the next edition of the book, and add more details to the docstring in the repository here.

**Comment by j2kun** [comment]
I should also add, we can do it this way because we're hiding the work of "combining the different coefficients into a single polynomial" inside the Polynomial data structure.[1] This is not a particularly efficient way to build the secret sharing scheme (probably by an order of magnitude), but it makes for a simple first chapter application :)

[1]: https://github.com/pim-book/programmers-introduction-to-mathematics/blob/master/secret-sharing/polynomial.py#L44-L63

**Comment by j2kun** [comment]
I pushed https://github.com/pim-book/programmers-introduction-to-mathematics/pull/11 for the improved docstring. Could you let me know if this resolves your confusion? (Either way, I will probably merge that PR, because it's clear this is ambiguous)

**Comment by pbalogh** [comment]
That is a great explanation! I am embarrassed to admit that it took me a moment to understand that splitting up (x - x_i) / (x_i - x_j) takes us to Polynomial([-xj / (xi - xj), 1.0 / (xi - xj)])  -- specifically, the intermediate mental steps of turning the fraction into two fractions x/(x_i - x_j)  - x_i/(x_i - x_j) and then grokking that one of them is actually just x^1 times a coefficient (1/(x_i - x_j), while the other is x^0 times that same coefficient times - x_i.

**Comment by pbalogh** [comment]
At any rate, I now see that single_term() returns a single addend in the sum, and not an actual coefficient in the final polynomial. Thank you!

**Comment by j2kun** [comment]
The steps you mentioned in https://github.com/pim-book/programmers-introduction-to-mathematics/issues/10#issuecomment-464832469 is par for the course in math, so it's good that you're practicing it. But I admit this is something that should be explained in more detail in the code, so I added that to #11 as well.

Thanks for your feedback and thanks for reading!

**Comment by joshmakinda** [comment]
Does it make a difference here that in the book it says:
"We had to break up the degree-1 polynomial (x − xj )/(xi − xj ) into its coefficients, which are a0 = −xj /(xi − xj ) and a1 = 1/(xi − xj ).".... i.e "(x - xj)" but in the code samples, and here just in this discussion it says "(x - x_i)", as in the book shows an "xj" in the numerator but the code shows an "x_i" in the numerator... ? Does that make much of a difference? Got confused by that a bit.
