### ISSUE TITLE
ERROR: python-coveralls 2.9.1 has requirement coverage==4.0.3,

### ISSUE THREAD

**Issue by hmishfaq** [pim-book/programmers-introduction-to-mathematics#13]
Hi, I am getting this while trying to create virtualenv

"ERROR: python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.1 which is incompatible."

Not sure how to resolve it.

**Comment by j2kun** [comment]
It looks like you have never versions of these packages installed than are in my requirements. I can try to update them.

**Comment by j2kun** [comment]
This is caused by https://github.com/z4r/python-coveralls/issues/66 and I have a quick patch to workaround it in https://github.com/pim-book/programmers-introduction-to-mathematics/pull/14.

**Comment by j2kun** [comment]
In the mean time you can fix it with `pip install pytest-cov==2.5.0`
