### ISSUE TITLE
translation publication inquiry

### ISSUE THREAD

**Issue by anemochore** [pim-book/programmers-introduction-to-mathematics#20]
Hi, I work for Hanbit Media, Inc., the largest IT publisher in Korea. 
We have translated and published many English programming books here. 
I think your book is also very helpful to Korean programmer readers. 
Do you have any plan for publication in foreign countries? 
If you are willing, I'll let our copyright agency contact you (again) to discuss the contract detail. 
I appreciate your quick response.

**Comment by j2kun** [comment]
No thanks!
