### ISSUE TITLE
Pedantic detail on precursor example to proof page 17

### ISSUE THREAD

**Issue by zugzwang-alt** [pim-book/programmers-introduction-to-mathematics#21]
The expression 
```latex
f(x) = \sum\limits_{i=0}^n y_i \cdot (\prod\limits_{j \neq i}^n \frac{x-x_j}{x_i - x_j})
```
is introduced on page 17. However, instead of starting at zero like the summation notation describes, you start at one. I am not sure if this example was just to get warmed up or if it really was the precursor explanation. Starting at zero here just seems to make more sense. Thoughts?

**Comment by j2kun** [comment]
My apologies. This is a typo that will be fixed in the second edition. The indexes should start at 0 when there are n+1 points. I had originally written it as indexed starting at 1, then changed it later to index from 0 and neglected to update all the instances of it indexing.
