### ISSUE TITLE
(x - x_i) or (x - x_j)?

### ISSUE THREAD

**Issue by lshagiev** [pim-book/programmers-introduction-to-mathematics#28]
Shouldn't it be (x - x_j) here, like in in formula from the book?

https://github.com/pim-book/programmers-introduction-to-mathematics/blob/4fff911bb7933381441a7acb141265fd87a2e09a/secret-sharing/interpolate.py#L35

**Comment by j2kun** [comment]
Indeed, and even matching the formula directly below it!
