### ISSUE TITLE
Can we have a table of content on https://pimbook.org/

### ISSUE THREAD

**Issue by liyuankui** [pim-book/programmers-introduction-to-mathematics#38]
Coming to github via https://pimbook.org/, kinda confused that there is no table of content available. 
And no way to know the outline unless I download the full EBook

**Comment by liyuankui** [comment]
To those who are looking for a TOC, here it is. 

[toc-a-programmers-introduction-to-mathematics.pdf](https://github.com/pim-book/programmers-introduction-to-mathematics/files/7183114/toc-a-programmers-introduction-to-mathematics.pdf)

**Comment by j2kun** [comment]
Good call. Added it in https://github.com/pim-book/pim-book.github.io/commit/686c8010a96904e5034dd1f5b46738a29937e736

Should be live shortly.
