### ISSUE TITLE
Exercise solutions for beginners. 

### ISSUE THREAD

**Issue by phpmind** [pim-book/programmers-introduction-to-mathematics#8]
We need solutions for all exercises which are given at end of the chapter.

**Comment by j2kun** [comment]
If you have a question about a specific problem, open an issue here: https://github.com/pim-book/exercises

And please be respectful. I'm just one person with limited time.

**Comment by phpmind** [comment]
J2kun, I did not mean to be harsh or something like that. I thought you might have solutions already, i asked for it.

I just wanted to say thanks for a great book. I just received yesterday. 
Thanks

**Comment by allandequeiroz** [comment]
Yeah, solutions would be nice to check against what we're doing.

Some people including myself may prefer to do the exercises, check and move forward instead of open a discussion thread and wait for any interaction. 

Community and discussion are nice but also consumes time.

**Comment by allandequeiroz** [comment]
Btw, great book!
